blog/config/routes.rb
Rails.application.routes.draw do

  resources :articles do
  resources :comments, only[:create, :update, :destroy]
  end
  devise_for :users

  root 'welcome#index'

end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user #un articulo tiene un usuario
  has_many :comments
  validates :title, presence:true,uniqueness:true
  validates :body, presence:true
  before_save :set_visits_count
  def update_visits_count
    self.update(visits_count: self.visits_count+1)

  end
  #antes de crear el blog reinicie el contador
  private

  def set_visits_count
    self.visits_count ||=0

  end
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

blog/app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :articles #un usuario tiene muchos articulos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #autentificador de devise
before_action :authenticate_user!, except:[:show,:idex]

#nos permite ahorrar lines de codigo que se repiten
# @article = Article.find(params[:id])
before_action :set_article, except:[:index,:new,:create]
#Get/article
  def index
     @articles =Article.all
    end
    #Get /articles/:id
  def show
    @article.update_visits_count
    @comment = Comment.new
    #where
  #  Article.where.not("id = ?",params[:id])
  end
  #Get /articles/new
  def new
    @article=Article.new
  end
  #Pots/article
  def create
    #current_user tiene la informacion del usuario
    @article= current_user.articles.new(article_params)
        if@article.save
        redirect_to @article
      else
        render :new
      end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end
  #
  def edit

  end
  #put/article/:id
  def update
    @article = Article.find(params[:id])
    if @article.update (article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  # si el usuario no ha iniciado sesion y intenta crear un blog lo redirige a el login
  def validate_user
    redirect_to new_user_session_path, notice:"Nesecitas iniciar sesion"
  end
  def article_params
    params.require(:article).permit(:title,:body)

  end

end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
      @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to   @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_article
      @comment = Comment.find(params[:article_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<h1><%= name %> Articulo</h1>
<%= form_for(@article) do |f|%>
<% @article.errors.full_messages.each do |message| %>
<div class="be-red white top-space">
  <%= message %>
</div>
<% end %>
<div class="field">
<%= f.text_field :title ,placeholder: "Titulo",class:"form-control"%>
</div>
<div class="field">
  <%= f.text_area :body,placeholder: "Escribe aqui el contenido",style:"height:250px",
  class:"form-control"%>
</div>
<div class="field">
  <%= f.submit "Guardar",class:"btn be-red white large-padding"%>
</div>
<% end %>

blog/app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
  
  <%= render "form",name:"Editar"%>
</div>

blog/app/views/articles/index.html.erb
<% @articles.each do |article|%>
<h1><%= link_to article.title, article %></h1>
<div class="">
  <%= article.body%>- <%= link_to "Eliminar", article, method: :delete%>
</div>
<% end %>

blog/app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">

  <%= render "form", name:"Crear"%>
  
</div>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil?%>
<p>Escrito por: <%=@article.user.email %></p>
<p>Visitas: <%=@article.visits_count %></p>
<% end %>
<div class="">
  <%= @article.body%>
</div>
<div class="field">
  <h3>Comentarios</h3>
  <%=render "comments/form" %>
  <ul>
    <% @article.comments.each do |comment| %>
    <li>
      <%= comment.body%>-<%= comment.user.email%>
    </li>
    <% end%>
  </ul>
</div>
<div class="">
  <%= link_to "Editar", edit_article_path(@article)%>
</div>

blog/app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |f| %>

  


  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render "partials/navigation"%>

    <%= yield %>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

blog/app/views/partials/_navigation.html.erb
<header>
  <nav class=" be-red white large-padding">
    <ul class="no-list row center-xs middle-xs">
      <li class="col-md">
          <h1 class="no-margin">Blog </h1>
      </li>
      <li class="col-md">
        <%= link_to "Inicio", root_path%>
      </li>
      <li class="col-md">
        Diseño
      </li>
      <li class="col-md">
        Programacion
      </li>
      <li class="col-md">
        Tecnologia
      </li>
      <% if user_signed_in?%>
      <li class="col-md">
        <%= link_to "cerrar sesion",  destroy_user_session_path,method: :delete%>
      </li>
      <% else%>
      <li class="col-md">
        <%= link_to "Iniciar sesion", new_user_session_path%>
      </li>
      <li class="col-md">
        <%= link_to "Crear Cuenta", new_user_registration_path%>
      </li>
      <% end %>

    </ul>
  </nav>
</header>

blog/app/views/welcome/index.html.erb
<% if user_signed_in?%>
<h1> Bienvenido <%= current_user.email%></h1>
<% end %>